services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
